
name: Release

on:
  workflow_run:
    workflows: ["Coverage"]
    branches: [main]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm i

      - name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump versions
        run: |
          npm run version:ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
